import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Header from '../components/header'
import Portfolio from '../components/portfolio'
import Client from '../components/client'

export default function Home() {
  return (
    <div>
      <Head>
        <title>BG Agency 123</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header></Header>
      
      <div class="w-full h-screen bg-[url('/images/portfolio/carsome/visual-carsome-video.jpg')] bg-cover bg-center">
        <div class="absolute inset-x-0 bottom-12 lg:bottom-20 text-center text-white text-2xl md:text-3xl lg:text-6xl uppercase">
          <h1 class="font-extralight">Creative Solutions</h1>
          <h1 class="font-semibold">For everyone</h1>
        </div>
      </div>
     
      <div id="About Us" class="py-16 px-4 text-center">
        <div class="md:w-8/12 lg:w-6/12 xl:w-4/12 mx-auto">
        <p>Bikin Gemes Agency is a creative service agency
with a disruptive business model.</p>
<p>Traditionally clients are bridged through Key Accounts, 
we, however, analyses your industry fields,
and find someone passionate in our team
to run your projects.</p>
<p>Bikin Gemes cabang Singapore</p>

<p class="mt-8">We believe in the joy of works
created by our enthusiast creatives. All these create
an enthusiastic persona of each creative works done.
</p>
        </div>
        

<p class="mt-8 uppercase text-4xl font-light">Pouring our passion into work</p>
<p class="uppercase font-bold text-4xl">Is no work at all</p>
      </div>

<Portfolio></Portfolio>

<div id="Clients"><Client></Client></div>


      <footer id="Contact" class="flex bg-black mx-auto py-20">
        <div class="mx-auto grid sm:grid-cols-3 gap-8 2xl:gap-10 2xl:max-w-screen-2xl">
          <div class="flex flex-col-reverse px-4"><Image src="/images/footer-logo.png" width={277} height={332} /></div>
          <div class="flex flex-col justify-between text-center">
            <div>
              <p class="text-gray-400 mb-8">Jakarta | Indonesia</p>
              <p class="text-white">New Business</p>
              <p class="text-gray-400 mb-8">Sheilla@bikingemes.com</p>
              <p class="text-white">Jobs</p>
              <p class="text-gray-400 mb-8">Sheilla@bikingemes.com</p>
            </div>
            <h3 class="text-2xl lg:text-5xl text-white font-bold uppercase">BG Agency</h3>
          </div>
          <div class="flex items-end justify-center sm:justify-end px-4">
            <Link class="mr-4" href="#"><Image src="/images/wa.png" width={50} height={50} /></Link>
            <Link href="#"><Image src="/images/ig.png" width={50} height={50} /></Link>
          </div>
        </div>
      </footer>
    </div>
  )
}
